from __future__ import annotations

from importlib import import_module
from typing import Any

_API_EXPORTS = [
    "EnterpriseSession",
    "SessionConfig",
    "SessionHook",
    "activate_workspace_contract_variant_entry",
    "activate_workspace_scenario_entry",
    "activate_workspace_scenario_variant_entry",
    "bootstrap_contract_from_import_bundle_entry",
    "bootstrap_workspace_contract_entry",
    "build_blueprint_asset_for_example_entry",
    "build_blueprint_asset_for_family_entry",
    "build_blueprint_asset_for_scenario_entry",
    "build_blueprint_for_family_entry",
    "build_blueprint_for_scenario_entry",
    "build_grounding_bundle_example_entry",
    "build_identity_flow_summary_entry",
    "build_release_version",
    "compile_blueprint_entry",
    "compile_identity_governance_bundle_entry",
    "compile_workflow_spec",
    "compile_workspace_entry",
    "create_session",
    "create_world_session_from_blueprint_entry",
    "create_workspace_from_template_entry",
    "create_workspace_scenario_entry",
    "diff_run_snapshots_entry",
    "diff_workspace_contract_entry",
    "export_mission_run_entry",
    "export_release_benchmark",
    "export_release_dataset",
    "filter_enterprise_corpus",
    "generate_enterprise_corpus",
    "generate_identity_scenario_candidates_entry",
    "generate_workspace_scenarios_from_import_entry",
    "get_benchmark_family_manifest_entry",
    "get_benchmark_family_workflow_spec",
    "get_benchmark_family_workflow_variant",
    "get_facade_manifest_entry",
    "get_facade_plugin_entry",
    "get_import_package_example_path_entry",
    "get_playable_mission_entry",
    "get_run_capability_graphs_entry",
    "get_run_orientation_entry",
    "get_scenario_manifest",
    "get_showcase_example_entry",
    "get_vertical_contract_variant_entry",
    "get_vertical_pack_manifest_entry",
    "get_vertical_scenario_variant_entry",
    "get_workspace_fidelity_report_entry",
    "import_workspace_entry",
    "launch_workspace_run_entry",
    "list_benchmark_family_manifest_entries",
    "list_benchmark_family_workflow_specs",
    "list_benchmark_family_workflow_variants",
    "list_blueprint_builder_examples_entries",
    "list_blueprint_entries",
    "list_facade_manifest_entries",
    "list_facade_plugin_entries",
    "list_grounding_bundle_example_entries",
    "list_import_package_example_entries",
    "list_playable_missions_entry",
    "list_run_manifests_entry",
    "list_run_snapshots_entry",
    "list_scenario_manifest",
    "list_showcase_example_entries",
    "list_vertical_contract_variant_entries",
    "list_vertical_pack_manifest_entries",
    "list_vertical_scenario_variant_entries",
    "list_workspace_contract_variants_entry",
    "list_workspace_playable_missions_entry",
    "list_workspace_runs_entry",
    "list_workspace_scenario_variants_entry",
    "list_workspace_scenarios_entry",
    "list_workspace_source_syncs_entry",
    "list_workspace_sources_entry",
    "load_import_package_entry",
    "load_okta_connector_config_entry",
    "load_run_events_entry",
    "load_run_manifest_entry",
    "load_run_timeline_entry",
    "load_workspace_contract_entry",
    "load_workspace_entry",
    "load_workspace_generated_scenarios_entry",
    "load_workspace_import_report_entry",
    "load_workspace_import_review_entry",
    "load_workspace_mission_state_entry",
    "load_workspace_provenance_entry",
    "normalize_import_package_entry",
    "prepare_identity_workspace_flow_entry",
    "prepare_playable_workspace_entry",
    "prepare_vertical_demo_entry",
    "preview_workspace_scenario_entry",
    "register_facade_plugin_entry",
    "review_import_package_entry",
    "run_benchmark_family_workflow",
    "run_playable_showcase_entry",
    "run_release_nightly",
    "run_vertical_showcase_entry",
    "run_vertical_variant_matrix_entry",
    "run_workflow_spec",
    "scaffold_mapping_override_entry",
    "show_workspace_entry",
    "sync_workspace_source_entry",
    "validate_benchmark_family_workflow",
    "validate_import_package_entry",
    "validate_workflow_spec",
    "validate_workspace_contract_entry",
]

__all__ = list(_API_EXPORTS)


def __getattr__(name: str) -> Any:
    if name not in _API_EXPORTS:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    module = import_module(".api", __name__)
    value = getattr(module, name)
    globals()[name] = value
    return value


def __dir__() -> list[str]:
    return sorted(list(globals().keys()) + list(__all__))
